config/routes.rb
Rails.application.routes.draw do
  resources :students, shallow: true do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def new
    @address = Address.new
    # @student = Student.find(params[:id])
    # @address = @student.create(address_params)
  end

  private
  def address_params
    params.require(:address).permit(:description, :street, :city, :state, :zip_code,)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def show
    @student = Student.find(params[:id])
  end

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)
    redirect_to students_path
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student = Student.update(student_params)
    redirect_to students_path
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy
    redirect_to students_path
  end


  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<h1>New Address</h1>
<%= form_for @address do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enrollment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
    <%= link_to 'All Students', students_path %>
    <%= link_to 'Create A Student', new_student_path %>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h1>Edit <%= @student.name %>'s Name</h1>
<%= form_for @student do |f| %>
  <%= f.label :student %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/students/index.html.erb
<h1>All Students:</h1>

<ul>
<% @students.each do |student| %>
  <li class=student_<%= student.id %>>
    <%= link_to student.name, student_path(student)  %>
    <%= link_to 'Delete', student_path(student), method: 'delete' %>
  </li>
  <%end%>
</ul>

app/views/students/new.html.erb
<h2>Create A Student:</h2>
<%= form_for @student do |f| %>
  <%= f.label :student %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/students/show.html.erb
<h1>Name: <%= @student.name %></h1>